service:
  name: example-app-deploy

provider:
  name: aws
  region: ap-southeast-2

resources:
  Resources:
    CodeBuildRole:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement: 
            - Effect: Allow
              Principal: 
                Service: 
                  - codebuild.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service.name}-build-policy
            PolicyDocument: 
              Version: '2012-10-17'
              Statement: 
                - Effect: Allow
                  Action:
                    - logs:*
                  Resource: '*'
                - Effect: Allow
                  Action: s3:PutObject
                  Resource: arn:aws:s3:::example-app-dev-frontpagewebsitebucket-19jr14sozhbv6
                - Effect: Allow
                  Action: cloudfront:CreateInvalidation
                  Resource: arn:aws:cloudfront::344260392803:distribution/E12MWEG8DY8FNG
    CodeBuildProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: ${self:service.name}
        Description: My website builder
        ServiceRole: !Ref CodeBuildRole
        Artifacts:
          Type: NO_ARTIFACTS
        BadgeEnabled: true
        Environment:
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:2.0
          Type: LINUX_CONTAINER
        Source:
          Location: https://github.com/kkesley/react-s3-blog-example.git
          Type: GITHUB
        Cache:
          Modes:
            - LOCAL_CUSTOM_CACHE
          Type: LOCAL